vim.keymap.set("", "<Space>", "<Nop>")
require("config.options")
require("config.lazy")
require("config.autocmds")
require("config.keymaps")
-- require("config.statusline")
-- require("config.winbar")
vim.cmd("colorscheme gruvbox-material")
vim.cmd('autocmd BufEnter * set formatoptions-=cro')
vim.cmd('autocmd BufEnter * setlocal formatoptions-=cro')

-- TODO: remove it from here
vim.api.nvim_set_hl(0, "CursorLineNr", { bold = true, fg = "#e2cca9" })
vim.api.nvim_set_hl(0, "BlinkCmpMenu", { bg = "#101317" })
-- vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { bg = "#141617", fg = 'grey', })
vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = "#101317" })
-- vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { bg = "#141617", fg = 'grey', })
-- vim.api.nvim_set_hl(0, "BlinkCmpDocSeparator", { bg = "#141617", fg = 'grey', })
